apiVersion: v1
kind: Service
metadata:
  name: sqc-frontend-service
spec:
  selector:
    app: sqc-frontend-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: sqc-backend-service
spec:
  selector:
    app: sqc-backend-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: sqc-ai-service
spec:
  selector:
    app: sqc-ai-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
