apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sqc-ingress
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  ingressClassName: alb
  rules:
    - host: sqcapp.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx
              port:
                number: 80
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: sqc-backend-service
              port:
                number: 80
        - path: /front
          pathType: Prefix
          backend:
            service:
              name: sqc-frontend-service
              port:
                number: 80