apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqc-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sqc-ai-pod
  template:
    metadata:
      labels:
        app: sqc-ai-pod
    spec:
      containers:
        - name: sqc-ai-pod
          image: wjdgns2/sqc-ai:latest
          envFrom:
            - secretRef:
                name: mongodb-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqc-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sqc-frontend-pod
  template:
    metadata:
      labels:
        app: sqc-frontend-pod
    spec:
      containers:
      - name: sqc-frontend-pod
        image: wjdgns2/sqc-frontend:latest


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqc-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sqc-backend-pod
  template:
    metadata:
      labels:
        app: sqc-backend-pod
    spec:
      containers:
      - name: sqc-backend-pod
        image: wjdgns2/sqc-backend:latest
        envFrom:
        - secretRef:
            name: mongodb-secret
